language: ruby
rvm:
  - 2.5.0
install: 
  - bundle install
  - gem install jekyll -v 3.4.3
  - gem install s3_website
  - gem install minimal-mistakes-jekyll

branches:
  only:
    - master
    - stage

script: JEKYLL_ENV=production bundle exec jekyll build
after_success: s3_website push